# Generated by Django 5.2.4 on 2025-08-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
