# Generated by Django 5.2.4 on 2025-08-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_public_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_status',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
