# Generated by Django 5.2.4 on 2025-08-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
    ]
